### ISSUE TITLE
zadd fails with AttributeError (example.py)

### ISSUE THREAD

**Issue by iTosun** [closeio/redis-hashring#8]
I tried to run the example.py to play with this library. Unfortunately it failed right away. What happens is that within the init of the RingNode replica's are made. This is a hughe list of tuples with timestamp, hostname + some identifier concated to it. 

What happens is when a heartbeat is made it tries to use zadd to submit the replica's to redis. The following is ran on line 207:
```
for replica in self.replicas:
            pipeline.zadd(self.key, '{start}:{name}'.format(
                start=replica[0],
                name=replica[1]
            ), now)
        ret = pipeline.execute()
```
so what happens here is that it concatnates a string of the timestamp + the unique hostname&identifier. But zadd will try the following on this:
```
for pair in iteritems(mapping):
    pieces.append(pair[1])
    pieces.append(pair[0])
```
Where the variable mapping is the replica string and iteritems has the following code within the redis library:
```
def iteritems(x):
   return iter(x.items())
```
We know that a string has no items attribute in python because it is not a iterator. So the whole example.py will fail without even touching redis.

**Comment by jkemp101** [comment]
This is most likely related to the backwards incompatibilities of the redis 3.x package. Can you try it with `pip install redis==2.10.6`.

**Comment by thomasst** [comment]
I'm closing this since we switched to redis-py 3 mpw. If still an issue, please provide a traceback.
